version: '3.1'
services:
  storage:
    image: redis
    volumes:
      - ./redis/data:/data

  library:
    image: jhonkikkoman/library:v1.0.0
    working_dir: /my-app
    volumes:
      - ./:/my-app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - storage

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./src/mongodb/data:/mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ./src/mongodb/data:/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    volumes:
      - ./src/mongodb/data:/mongodb
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongo
